name: Scheduled Check

on:
  push:
    branches:
      - main
  # schedule:
  #   # UTC 17時に実行
  #   - cron: "0 8 * * *"

jobs:
  check:
    name: Check if App is functional
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Set up Playwright Env
        uses: microsoft/playwright-github-action@v1
      - name: Install package
        run: npm install
      - name: functional E2E test
        run: npm run test:ci:functional
        env:
          TARGET_URL: https://ml-playground-fe-git-develop-yuya-okada527.vercel.app
